### ISSUE TITLE
NameError: global name 'LLDPChassisId' is not defined

### ISSUE THREAD

**Issue by buptmuye** [jliendo/topodiscovery#1]
Glad to see topodiscovery project.
However, when i start pox and mininet, it gave me such error:

  File "/home/muye/pox/ext/test.py", line 223, in send_LLDP
    LLDPTTL(seconds = self.lldp_ttl)/\
NameError: global name 'LLDPChassisId' is not defined

I am very confused and hope for your guide.

**Comment by lordlabakdas** [comment]
I get the same error  while trying out topodiscovery using POX and Mininet.
 
`Traceback (most recent call last):`
   ` File "/resilinets/code/pox/lib/recoco/recoco.py", line 273, in cycle`
    `rv = t.execute()`
  `File "/resilinets/code/pox/lib/recoco/recoco.py", line 91, in execute`
    `return self.gen.send(v)`
  `File "/resilinets/code/pox/lib/recoco/recoco.py", line 748, in run`
    `rv = self._callback(*self._args,**self._kw)`
  `File "/resilinets/code/ext/misc/discovery.py", line 224, in send_LLDP`
    `LLDPTTL(seconds = self.lldp_ttl)/\`
`NameError: global name 'LLDPChassisId' is not defined`
